version: '2.1'

services:
  codecept:
    image: reform/codeceptjs:latest
    command: bash -c "./xvfb-run.sh yarn test-e2e"
    environment:
      E2E_FRONTEND_URL: ${TEST_URL:-https://localhost:8080}
    volumes:
      - "../.:/tests"